# name of workflow, usually match the name of the file.yml
name: gh        

on:
  push:         # to be called on push to the repo,  can be disabled if you want to run it manually 
    paths:      # only if this file is pushed, then the workflow will be triggered
      - ".github/workflows/gh.yml"
  workflow_dispatch: # manual

jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: env
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
      - run: gh issue list
      - run: gh workflow list
      - run: gh api /repos/:owner/:repo/actions/workflows